services:  
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: passwordManagerService
      MYSQL_USER: dev
      MYSQL_PASSWORD: developer
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD_FILE: /run/secrets/db_developer_password
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/0.sql
      # - ./database/state:/var/lib/mysql
    # secrets:
    #   - db_root_password
    #   - db_developer_password
  
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_LINK: passwordmanager-db-1:3306
      DATABASE: passwordManagerService
      SIGNING_KEY: passwordManagerService
      REDIS_LINK: cache:6379
      REDIS_PASSWORD: cache
      SECRET_KEY: N1PCdw3M2B1TfJhoaY2mL736p2vCUc47

  ui:
    build: ./ui
    ports:
      - 3000:3000
    depends_on:
      - api
  
  cache:
    image: redis:7.2.3
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cache
    volumes: 
      - ./cache/state:/data

# secrets:
#   db_developer_password:
#     file: ./database/secrets/db_developer_password.txt
#   db_root_password:
#     file: ./database/secrets/db_root_password.txt